-- Create threads table
CREATE TABLE IF NOT EXISTS threads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID REFERENCES listings(id) ON DELETE CASCADE,
    host_id UUID REFERENCES users(id) ON DELETE CASCADE,
    seeker_id UUID REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create messages table
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id UUID REFERENCES threads(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    read_at TIMESTAMPTZ
);

-- Enable RLS
ALTER TABLE threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- RLS for threads
CREATE POLICY "Users can view threads they practice in" ON threads
    FOR SELECT USING (auth.uid() = host_id OR auth.uid() = seeker_id);

CREATE POLICY "Users can create threads" ON threads
    FOR INSERT WITH CHECK (auth.uid() = seeker_id);

-- RLS for messages
CREATE POLICY "Users can view messages in their threads" ON messages
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM threads
            WHERE threads.id = messages.thread_id
            AND (threads.host_id = auth.uid() OR threads.seeker_id = auth.uid())
        )
    );

CREATE POLICY "Users can insert messages in their threads" ON messages
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM threads
            WHERE threads.id = messages.thread_id
            AND (threads.host_id = auth.uid() OR threads.seeker_id = auth.uid())
        )
    );
