-- Create table for Before/After posts
create table if not exists public.before_after_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  before_image_url text not null,
  after_image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.before_after_posts enable row level security;

create policy "Enable read access for all users"
on public.before_after_posts for select
using (true);

create policy "Enable insert for authenticated users only"
on public.before_after_posts for insert
with check (auth.uid() = user_id);

create policy "Enable update for users based on user_id"
on public.before_after_posts for update
using (auth.uid() = user_id);

create policy "Enable delete for users based on user_id"
on public.before_after_posts for delete
using (auth.uid() = user_id);
