-- Create reviews table
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  listing_id uuid references public.listings(id) not null,
  user_id uuid references auth.users not null,
  rating integer check (rating >= 1 and rating <= 5) not null,
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.reviews enable row level security;

create policy "Reviews are viewable by everyone"
on public.reviews for select
using (true);

create policy "Authenticated users can create reviews"
on public.reviews for insert
with check (auth.role() = 'authenticated');
